/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AirtestControl: typeof import('./src/components/python/airtest/airtestControl.vue')['default']
    AllFilePath: typeof import('./src/components/allFilePath.vue')['default']
    AllPrint: typeof import('./src/components/allPrint.vue')['default']
    AllSelect: typeof import('./src/components/allSelect.vue')['default']
    CustomPyControl: typeof import('./src/components/python/custom/customPyControl.vue')['default']
    HeaderIndex: typeof import('./src/components/headerIndex.vue')['default']
    HomePage: typeof import('./src/components/home/homePage.vue')['default']
    HomeSidebar: typeof import('./src/components/sidebar/homeSidebar.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    OtherControl: typeof import('./src/components/Script/puppeteerBilibili/otherControl.vue')['default']
    OtherPyControl: typeof import('./src/components/python/custom/otherPyControl.vue')['default']
    OthoerControl: typeof import('./src/components/Script/othoer/othoerControl.vue')['default']
    PuppeteerBilibiliControl: typeof import('./src/components/Script/puppeteerBilibili/puppeteerBilibiliControl.vue')['default']
    PuppeteerControl: typeof import('./src/components/Script/puppeteerPixiv/puppeteerControl.vue')['default']
    PuppeteerPage: typeof import('./src/components/Script/puppeteerPage.vue')['default']
    PuppeteerPixivControl: typeof import('./src/components/Script/puppeteerPixiv/puppeteerPixivControl.vue')['default']
    PuppeteerSelect: typeof import('./src/components/Script/puppeteerSelect.vue')['default']
    PythonControl: typeof import('./src/components/python/pythonControl.vue')['default']
    PythonorControl: typeof import('./src/components/python/other/pythonorControl.vue')['default']
    PythonPage: typeof import('./src/components/python/pythonPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptAllControl: typeof import('./src/components/Script/scriptAllControl.vue')['default']
    ScriptControl: typeof import('./src/components/Script/scriptControl.vue')['default']
    ScriptPage: typeof import('./src/components/Script/scriptPage.vue')['default']
    ScriptSelect: typeof import('./src/components/scriptSelect.vue')['default']
    SettingAll: typeof import('./src/components/settings/settingAll.vue')['default']
    SettingGlobal: typeof import('./src/components/settings/settingGlobal.vue')['default']
    SettingPuppeteer: typeof import('./src/components/settings/settingPuppeteer.vue')['default']
    SettingPython: typeof import('./src/components/settings/settingPython.vue')['default']
    SettingsPage: typeof import('./src/components/settings/settingsPage.vue')['default']
    SidebarButton: typeof import('./src/components/sidebar/sidebarButton.vue')['default']
    WindowsControl: typeof import('./src/components/windowsControl.vue')['default']
  }
}
