/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AirtestControl: typeof import('./src/components/python/airtest/airtestControl.vue')['default']
    AllFilePath: typeof import('./src/components/allFilePath.vue')['default']
    AllPrint: typeof import('./src/components/allPrint.vue')['default']
    AllSelect: typeof import('./src/components/allSelect.vue')['default']
    ChromeWindowControl: typeof import('./src/components/chrome/chromeWindowControl.vue')['default']
    CustomPyControl: typeof import('./src/components/python/custom/customPyControl.vue')['default']
    FooterIndex: typeof import('./src/components/footerIndex.vue')['default']
    HeaderChromeIndex: typeof import('./src/components/chrome/headerChromeIndex.vue')['default']
    HeaderIndex: typeof import('./src/components/headerIndex.vue')['default']
    HomePage: typeof import('./src/components/home/homePage.vue')['default']
    HomeSidebar: typeof import('./src/components/sidebar/homeSidebar.vue')['default']
    MoeCounter: typeof import('./src/components/moeCounter.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PageControl: typeof import('./src/components/pageControl.vue')['default']
    PuppeteerBilibiliControl: typeof import('./src/components/Script/puppeteerBilibili/puppeteerBilibiliControl.vue')['default']
    PuppeteerPixivControl: typeof import('./src/components/Script/puppeteerPixiv/puppeteerPixivControl.vue')['default']
    PythonControl: typeof import('./src/components/python/pythonControl.vue')['default']
    PythonPage: typeof import('./src/components/python/pythonPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptControl: typeof import('./src/components/Script/scriptControl.vue')['default']
    ScriptPage: typeof import('./src/components/Script/scriptPage.vue')['default']
    SettingGlobal: typeof import('./src/components/settings/settingGlobal.vue')['default']
    SettingPython: typeof import('./src/components/settings/settingPython.vue')['default']
    SettingScript: typeof import('./src/components/settings/settingScript.vue')['default']
    SettingsPage: typeof import('./src/components/settings/settingsPage.vue')['default']
    SharpCompress: typeof import('./src/components/tool/sharp/sharpCompress.vue')['default']
    SharpControl: typeof import('./src/components/sharpControl.vue')['default']
    SharpFormat: typeof import('./src/components/tool/sharp/sharpFormat.vue')['default']
    SharpFormatConversion: typeof import('./src/components/tool/sharp/sharpFormatConversion.vue')['default']
    SharpHeaderSetting: typeof import('./src/components/tool/sharp/sharpHeaderSetting.vue')['default']
    SharpImage: typeof import('./src/components/tool/sharp/sharpImage.vue')['default']
    SharpTool: typeof import('./src/components/tool/sharp/sharpTool.vue')['default']
    SidebarButton: typeof import('./src/components/sidebar/sidebarButton.vue')['default']
    ToolControl: typeof import('./src/components/toolControl.vue')['default']
    ToolPage: typeof import('./src/components/tool/toolPage.vue')['default']
    WindowsControl: typeof import('./src/components/windowsControl.vue')['default']
  }
}
