/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllFilePath: typeof import('./src/components/allFilePath.vue')['default']
    AllPrint: typeof import('./src/components/allPrint.vue')['default']
    HeaderIndex: typeof import('./src/components/headerIndex.vue')['default']
    HomePage: typeof import('./src/components/home/homePage.vue')['default']
    HomeSidebar: typeof import('./src/components/sidebar/homeSidebar.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PuppeteerControl: typeof import('./src/components/puppeteer/puppeteerControl.vue')['default']
    PuppeteerPage: typeof import('./src/components/puppeteer/puppeteerPage.vue')['default']
    PythonControl: typeof import('./src/components/python/pythonControl.vue')['default']
    PythonPage: typeof import('./src/components/python/pythonPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingPuppeteer: typeof import('./src/components/settings/settingPuppeteer.vue')['default']
    SettingPython: typeof import('./src/components/settings/settingPython.vue')['default']
    SettingsPage: typeof import('./src/components/settings/settingsPage.vue')['default']
    SidebarButton: typeof import('./src/components/sidebar/sidebarButton.vue')['default']
    WindowsControl: typeof import('./src/components/windowsControl.vue')['default']
  }
}
